**Assignment 1 Solution** <br>
Importing Required Libraries

In [1]:
import pandas as pd
import numpy as np

**PART 1** <br>
Opening csv file and displaying rows

In [2]:
data = pd.read_csv('./california_housing_train.csv')
print(data[:5])
print(data[-10:]) #using negative index for displaying last rows

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124

Displaying Statiscal Summary of dataframe using `.describe()`

In [3]:
summary = data.describe()
print(summary)

          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.00000

Finding Unique Values in Column using `numpy.unique()`

In [4]:
total_bedrooms = np.array(data['total_bedrooms'])
unique_bedrooms = np.unique(total_bedrooms)
print('Unique Values \n',unique_bedrooms)
print('No. of Unique Values: ',len(unique_bedrooms))

Unique Values 
 [1.000e+00 2.000e+00 3.000e+00 ... 5.290e+03 5.471e+03 6.445e+03]
No. of Unique Values:  1848


Creating New Column in Dataframe

In [5]:
data['total_bedrooms_per_total_rooms'] = data['total_bedrooms'] / data['total_rooms']

Calculating mean and standard deviation of column using `.mean()` and `.std()`

In [6]:
m = data['total_bedrooms_per_total_rooms'].mean()
sd = data['total_bedrooms_per_total_rooms'].std()
print('mean is: ',m)
print('standard deviation is: ',sd)

mean is:  0.21275998821034803
standard deviation is:  0.05782300890316167


Filter data for Single Column Condition

In [7]:
filter_data = data[data['median_income'] > 5]
print(filter_data)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  media

Making a subset dataframe by filtering dataframe for multiple column condition using `.query()`

In [8]:
sdata = data.query('total_rooms > 10000 and median_house_value < 150000')
print(sdata)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  media

Saving Dataframe as csv file

In [9]:
sdata.to_csv('subsetdata.csv')

**PART 2** <br>
Creating a numpy array using `numpy.arange()`

In [10]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Slicing Numpy array

In [11]:
b = a[1::2] # sliced array starts from index 1 with step size of 2
print(b)

[ 2  4  6  8 10 12 14 16 18 20]


Generating Random arrays

In [12]:
rng = np.random.default_rng() # creating a generator
r = rng.integers(low = 10, high= 100, size = (5,4)) #creating random array of integers between 10 and 100 
print(r)

[[29 28 77 34]
 [23 66 36 54]
 [80 60 75 68]
 [87 65 30 17]
 [98 90 99 66]]


Slicing 2D Numpy Array

In [13]:
new_r = r[:3,:2]
print(new_r)

[[29 28]
 [23 66]
 [80 60]]


Reshaping and Flattening Array using `.reshape()` and `.flatten()`

In [14]:
new_a = a.reshape(4,5)
print(new_a)
flattened_a = new_a.flatten()
print(flattened_a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Generating random 2D array and using mathmul operator `@` for matrix multiplication

In [15]:
r2 = rng.integers(100, size= (4,5))
print(new_a @ r2.T) #Taking Transpose for dimension matching for multiplication

[[1049  673  458  656]
 [2614 1793 1063 1741]
 [4179 2913 1668 2826]
 [5744 4033 2273 3911]]


Creating a NumPy array of 50 random integers between 0 and 100 and using `numpy.where()` for finding where value is greater than 50

In [16]:
r3 = rng.integers(0, 100, size= 50)
r3b = r3[np.where(r3>50)]
print(r3b)

[67 91 57 74 99 82 93 66 55 98 67 77 99 75 70 83 90 83 52 57]


Using Fancy Indexing

In [17]:
i = rng.integers(0, len(r3)-1, size= 10, endpoint= True) #generating random array of indexes
print('Indexes are: ', i)
print(r3[i])

Indexes are:  [15 21 30 20 22 33 43 49 47 38]
[93 44 99 55  1 70 18 57 52 50]


Calculating mean,max,sum,min along each column

In [18]:
#Setting axis = 0 for calculating mean, sum, min, max along columns
mean= r.mean(axis=0)
print('Mean: ',mean)
sum = r.sum(axis=0)
print('Sum: ',sum)
min = r.min(axis=0)
print('Min: ',min)
max = r.max(axis=0)
print('Max: ',max)

Mean:  [63.4 61.8 63.4 47.8]
Sum:  [317 309 317 239]
Min:  [23 28 30 17]
Max:  [98 90 99 68]


Creating mask and Displaying Filtered Array

In [19]:
mask_r = np.where(r > mean ,True, False)
print(mask_r)
filtered_r = np.ma.masked_array(r, np.invert(mask_r)) #inverting mask since np.ma.masked_array() does not show elements having True value in mask
print(filtered_r)

[[False False  True False]
 [False  True False  True]
 [ True False  True  True]
 [ True  True False False]
 [ True  True  True  True]]
[[-- -- 77 --]
 [-- 66 -- 54]
 [80 -- 75 68]
 [87 65 -- --]
 [98 90 99 66]]


**PART 3** <br>
Printing first 100 elements of fibonacci series

In [20]:
a0 = 0
a1 =1
print(a0)
print(a1)
i= 1
while i <99:
    print(a0+a1)
    a= a0
    a0 =a1
    a1 = a+a1
    i+=1

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
754011380474634642

Using Loops and Divisibility in Python

In [21]:
i =1
while i <= 50:
    if i%3 == 0 and i%5 == 0:
        print('FizzBuzz')
    elif i%3 == 0:
        print('Fizz')
    elif i%5 == 0:
        print('Buzz')
    i+=1

Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Buzz


Showing median of list of numbers given <br>
Sample Input:
`12 34 65 784 435`

In [22]:
p = [int(x) for x in input().split()]
p = np.array(p)
p = np.sort(p)
m_i = int(len(p)/2)
print(p[m_i])

8


Calculating average of variable number of given numbers <br>
Sample Input: `12 34 65 784 435`

In [23]:
sum = 0
n = 0
for x in input().split():
    sum += int(x)
    n+=1
if n !=0:
    avg = sum/n
    print(avg)
else:
    print('ERROR: DIVISION BY ZERO')

8.0


**PART 4** <br>
Generating a random 3D array and swapping two of its axes using `numpy.swapaxes()`

In [24]:
arr3d = rng.integers(0, 100, size= (5,6,7))
print(arr3d)
s_arr3d = np.swapaxes(arr3d,1,2)
print('Swapped Array:\n',s_arr3d)

[[[43 63 78 12 24 75 31]
  [ 2 26  6  4 18 25 72]
  [70 35 93 72 98 44 45]
  [54 23 28 59  5 28 58]
  [35 98 65 65 96 91 68]
  [ 4 11 58  8 42 98 47]]

 [[59 17 54 89 38 71 53]
  [38 67 39 82 23 36 34]
  [53 64 38 88 82 92  9]
  [80 90 63 10 51 18 83]
  [65 62 70 39 82 81  8]
  [95 34 36 95 73 56 99]]

 [[90 41  5 89 15 12 79]
  [33 37 20 54 77 33 56]
  [75 99 82 31 98  3 62]
  [11 65 55 22 10 19 24]
  [ 2 85 82 68 21 30 62]
  [83 95 99 29 98 61 12]]

 [[74 85 84 49 91 38 23]
  [ 4 31 59 19 98 54 68]
  [93  3 86 86 84 86 61]
  [90 77  2 24 36 54 20]
  [31 39 64 72 72 92 15]
  [88 56 86  7 32 66 59]]

 [[82 87 39 77 11 97  8]
  [71 41 78 22  7 10 10]
  [36 30 15 46 89 43 25]
  [84 13 11 31 83 52 11]
  [13 66 24 52 30 75 35]
  [91 20 95 24 27 90 22]]]
Swapped Array:
 [[[43  2 70 54 35  4]
  [63 26 35 23 98 11]
  [78  6 93 28 65 58]
  [12  4 72 59 65  8]
  [24 18 98  5 96 42]
  [75 25 44 28 91 98]
  [31 72 45 58 68 47]]

 [[59 38 53 80 65 95]
  [17 67 64 90 62 34]
  [54 39 38 63 70 36]
  

Calculating sum of 3D array along any axis 

In [25]:
sum = np.sum(arr3d, axis=0)
print(sum)

[[348 293 260 316 179 293 194]
 [148 202 202 181 223 158 240]
 [327 231 314 323 451 268 202]
 [319 268 159 146 185 171 196]
 [146 350 305 296 301 369 188]
 [361 216 374 163 272 371 239]]


Generating a 2D array and 1D array using broadcasting add both the arrays

In [29]:
arr2d = rng.integers(0, 100, size= (6,7))
r_array = rng.integers(0, 100, size=7) #Of size 7 for dimension matching
print('2D array:\n', arr2d)
print('1D array:\n', r_array)
sum = arr2d + r_array
print('Array Sum:\n', sum)

2D array:
 [[37 31  0  2 93  9 12]
 [64 87 17 40 20 68  7]
 [ 9  8 26 77 90 66 22]
 [69 13 31 38 10 88 63]
 [ 0 46  8 28 47 34 16]
 [92  8 98  6 84 52 10]]
1D array:
 [13 64 11 34 19 72 57]
Array Sum:
 [[ 50  95  11  36 112  81  69]
 [ 77 151  28  74  39 140  64]
 [ 22  72  37 111 109 138  79]
 [ 82  77  42  72  29 160 120]
 [ 13 110  19  62  66 106  73]
 [105  72 109  40 103 124  67]]
